version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
 redis-net:
  driver: bridge