name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for building the Spring Boot app)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' or another Java distribution (e.g., 'zulu', 'adopt')
          java-version: '11'

      # Step 3: Build the Spring Boot application using Maven
      - name: Build with Maven
        run: mvn clean package  # Ensure your pom.xml file is in the root of the repo

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Adjust if your Dockerfile is in a subdirectory
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest
